# -----------------------------------------------------------------------------
# Copyright (c) 2020, Lucid Vision Labs, Inc.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# -----------------------------------------------------------------------------


XSAVE_STR_BUF_SIZE_DEFAULT = 500
XSAVE_STR_BUFFER_SIZE_1000 = 1000

#from math import inf

'''
AC_INFINITE = 0xFFFFFFFFFFFFFFFF  # 18446744073709551615
GET_BUFFER_TIMEOUT_MILLISEC_DEFAULT = inf
WAIT_ON_EVENT_TIMEOUT_MILLISEC_DEFAULT = inf
UPDATE_DEVICES_TIMEOUT_MILLISEC_DEFAULT = 1000  # SPECS STANDARD
NUM_OF_BUFFERS_DEFAULT = 10
XSAVE_STR_BUFFER_SIZE_DEFAULT = 500
XSAVE_STR_BUFFER_SIZE_1000 = 1000

'''
